[package]
name = "xcrust"
version = "0.1.0"
authors = ["Greg Hale <imalsogreg@gmail.com>"]
edition = "2018"

[dependencies]
clap   = "2.33.0"
chrono = "0.4.7"

[lib]
name = "xcrust"
src  = "src/lib.rs"

[[bin]]
name = "xcrust-hello"

[[bin]]
name = "xcrust-cat-spikes"